<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'; import AutoComplete from 'primevue/autocomplete'; import InputNumber from 'primevue/inputnumber'; import Button from 'primevue/button'; import Card from 'primevue/card'; import Message from 'primevue/message'; import ProgressSpinner from 'primevue/progressspinner'; import DataTable from 'primevue/datatable'; import Column from 'primevue/column'; import Tag from 'primevue/tag'; import { useToast } from 'primevue/usetoast';
import { useWrMetricManagement,getErrorMessage } from '../../application/useWrMetricManagement'; import type { Prospect } from '@/types'; import type { ManualWrMetricRequest,WrMetricRecord } from '../../domain/WrMetricTypes'; import { postDraftWrMetricsApi } from '../../infrastructure/PostDraftWrMetricsApi'; import WrMetricProvenanceTable from '../components/WrMetricProvenanceTable.vue'; import WrMetricManualDialog from '../components/WrMetricManualDialog.vue'; import WrMetricCsvImportDialog from '../components/WrMetricCsvImportDialog.vue'; import WrMetricVerificationDialog from '../components/WrMetricVerificationDialog.vue'
const manager=useWrMetricManagement(); const toast=useToast(); const manualVisible=ref(false),csvVisible=ref(false),verificationVisible=ref(false),saving=ref(false),dialogError=ref(''),editingRecord=ref<WrMetricRecord|null>(null),verificationRecord=ref<WrMetricRecord|null>(null),verificationAction=ref<'verify'|'unverify'>('verify');
const years=Array.from({length:16},(_,i)=>new Date().getFullYear()+2-i)
function prospectLabel(p:Prospect){return `${p.firstName} ${p.lastName} — ${p.college||'Unknown college'}`}
async function search(e:{query:string}){await manager.searchProspects(e.query)}
async function selectProspect(){await manager.loadResolved()}
function openNew(){editingRecord.value=null;dialogError.value='';manualVisible.value=true}
function openEdit(record:WrMetricRecord){editingRecord.value=record;dialogError.value='';manualVisible.value=true}
async function save(payload:ManualWrMetricRequest){saving.value=true;dialogError.value='';try{await manager.saveManual(payload);manualVisible.value=false;toast.add({severity:'success',summary:'Saved',detail:'WR metric record saved.',life:3000})}catch(e:unknown){dialogError.value=getErrorMessage(e)}finally{saving.value=false}}
function openVerification(record:WrMetricRecord,action:'verify'|'unverify'){verificationRecord.value=record;verificationAction.value=action;verificationVisible.value=true}
async function confirmVerification(notes:string){if(!verificationRecord.value)return;saving.value=true;try{const fn=verificationAction.value==='verify'?postDraftWrMetricsApi.verify:postDraftWrMetricsApi.unverify;await fn(verificationRecord.value.id,{notes:notes||null});verificationVisible.value=false;await manager.loadResolved();toast.add({severity:'success',summary:'Updated',detail:`Record ${verificationAction.value==='verify'?'verified':'unverified'}.`,life:3000})}catch(e:unknown){toast.add({severity:'error',summary:'Verification failed',detail:getErrorMessage(e),life:6000})}finally{saving.value=false}}
watch(()=>manager.draftYear.value,async()=>{manager.selectedProspect.value=null;manager.resolved.value=null;await manager.searchProspects()})
onMounted(()=>manager.searchProspects())
</script>
<template><main class="page"><header><div><p class="eyebrow">Post-Draft Analytics</p><h1>WR Metric Ingestion</h1><p>Manage advanced wide receiver metrics, verification, provider resolution, and provenance.</p></div><div class="actions"><Button label="Import CSV" icon="pi pi-upload" @click="csvVisible=true"/><Button label="New Manual Record" icon="pi pi-plus" :disabled="!manager.selectedProspect.value?.id" @click="openNew"/></div></header>
<Card><template #content><div class="filters"><label>Draft Year<InputNumber v-model="manager.draftYear.value" :useGrouping="false" :min="2012" :max="years[0]" /></label><label>WR Prospect<AutoComplete v-model="manager.selectedProspect.value" :suggestions="manager.prospects.value" optionLabel="firstName" dropdown forceSelection @complete="search" @item-select="selectProspect"><template #option="slotProps">{{prospectLabel(slotProps.option)}}</template><template #value="slotProps">{{slotProps.value?prospectLabel(slotProps.value):''}}</template></AutoComplete></label><Button label="Refresh" icon="pi pi-refresh" :disabled="!manager.selectedProspect.value" @click="manager.loadResolved"/></div></template></Card>
<Message v-if="manager.errorMessage.value" severity="error" :closable="false">{{manager.errorMessage.value}}</Message><ProgressSpinner v-if="manager.loading.value"/>
<section v-if="manager.selectedProspect.value && manager.resolved.value" class="stack"><Card><template #title>Resolved Metric Provenance</template><template #content><WrMetricProvenanceTable :metrics="manager.resolved.value"/></template></Card><Card><template #title>Source Records</template><template #content><DataTable :value="manager.records.value" dataKey="id" stripedRows responsiveLayout="scroll"><Column field="id" header="ID"/><Column field="sourceName" header="Source"/><Column field="sourceType" header="Type"/><Column field="seasonYear" header="Season"/><Column header="Verified"><template #body="{data}"><Tag :value="data.verified?'Verified':'Unverified'" :severity="data.verified?'success':'warning'"/></template></Column><Column field="verifiedAt" header="Verified At"/><Column field="verifiedBy" header="Verified By"/><Column field="sourceReference" header="Reference"/><Column header="Actions"><template #body="{data}"><div class="row-actions"><Button icon="pi pi-pencil" text rounded @click="openEdit(data)"/><Button v-if="!data.verified" label="Verify" text @click="openVerification(data,'verify')"/><Button v-else label="Unverify" text severity="warning" @click="openVerification(data,'unverify')"/></div></template></Column></DataTable></template></Card></section>
<WrMetricManualDialog v-model="manualVisible" :prospect-id="manager.selectedProspect.value?.id??0" :draft-year="manager.draftYear.value" :record="editingRecord" :saving="saving" :server-error="dialogError" @save="save"/><WrMetricCsvImportDialog v-model="csvVisible" @imported="manager.loadResolved"/><WrMetricVerificationDialog v-model="verificationVisible" :action="verificationAction" :loading="saving" @confirm="confirmVerification"/></main></template>
<style scoped>.page,.stack{display:grid;gap:1rem;padding:1rem}.page header{display:flex;justify-content:space-between;gap:1rem;background:var(--surface-card);padding:1rem;border-radius:1rem}.eyebrow{margin:0;color:var(--text-color-secondary);text-transform:uppercase;font-size:.75rem;letter-spacing:.08em}h1{margin:.25rem 0}.actions,.filters,.row-actions{display:flex;gap:.75rem;align-items:end;flex-wrap:wrap}.filters label{display:grid;gap:.35rem;min-width:13rem}@media(max-width:760px){.page header{flex-direction:column}}</style>
