<script setup lang="ts">
import { reactive, watch } from 'vue'
import Dialog from 'primevue/dialog'; import Button from 'primevue/button'; import InputNumber from 'primevue/inputnumber'; import InputText from 'primevue/inputtext'; import Dropdown from 'primevue/dropdown'; import Checkbox from 'primevue/checkbox'; import Message from 'primevue/message'
import type { ManualWrMetricRequest, WrMetricRecord } from '../../domain/WrMetricTypes'
const props = defineProps<{ modelValue:boolean; prospectId:number; draftYear:number; record?:WrMetricRecord|null; saving?:boolean; serverError?:string }>()
const emit = defineEmits<{ 'update:modelValue':[boolean]; save:[ManualWrMetricRequest] }>()
const form = reactive<ManualWrMetricRequest>({ prospectId:0,draftYear:0,seasonYear:0,yardsPerRouteRun:null,receivingGrade:null,contestedCatchRate:null,behindLosTargetRate:null,catchRate:null,missedTacklesForcedPerReception:null,yacAfterContactPerReception:null,sourceName:'Manual Entry',sourceType:'MANUAL',sourceReference:null,notes:null,verified:false })
const errors = reactive<Record<string,string>>({})
watch(() => props.modelValue, open => { if (!open) return; Object.assign(form,{ prospectId:props.prospectId,draftYear:props.draftYear,seasonYear:props.record?.seasonYear ?? props.draftYear-1,yardsPerRouteRun:props.record?.yardsPerRouteRun ?? null,receivingGrade:props.record?.receivingGrade ?? null,contestedCatchRate:props.record?.contestedCatchRate ?? null,behindLosTargetRate:props.record?.behindLosTargetRate ?? null,catchRate:props.record?.catchRate ?? null,missedTacklesForcedPerReception:props.record?.missedTacklesForcedPerReception ?? null,yacAfterContactPerReception:props.record?.yacAfterContactPerReception ?? null,sourceName:props.record?.sourceName ?? 'Manual Entry',sourceType:props.record?.sourceType ?? 'MANUAL',sourceReference:props.record?.sourceReference ?? null,notes:props.record?.notes ?? null,verified:props.record?.verified ?? false,id:props.record?.id}); Object.keys(errors).forEach(k=>delete errors[k]) })
function range(name:string,value:number|null,min:number,max:number){ if(value!==null&&(value<min||value>max)) errors[name]=`Must be between ${min} and ${max}.` }
function submit(){ Object.keys(errors).forEach(k=>delete errors[k]); if(!form.sourceName.trim()) errors.sourceName='Source name is required.'; if(form.seasonYear>form.draftYear+1) errors.seasonYear='Season year is materially later than draft year.'; range('yardsPerRouteRun',form.yardsPerRouteRun,0,10); range('receivingGrade',form.receivingGrade,0,100); range('contestedCatchRate',form.contestedCatchRate,0,100); range('behindLosTargetRate',form.behindLosTargetRate,0,100); range('catchRate',form.catchRate,0,100); range('missedTacklesForcedPerReception',form.missedTacklesForcedPerReception,0,5); range('yacAfterContactPerReception',form.yacAfterContactPerReception,0,20); if(Object.keys(errors).length===0) emit('save',{...form}) }
</script>
<template><Dialog :visible="modelValue" modal header="Manual WR Metric Record" :style="{width:'min(58rem,95vw)'}" @update:visible="emit('update:modelValue',$event)">
<Message v-if="serverError" severity="error" :closable="false">{{serverError}}</Message>
<div class="grid"><label>Draft Year<InputNumber v-model="form.draftYear" :useGrouping="false" /></label><label>Season Year<InputNumber v-model="form.seasonYear" :useGrouping="false" /><small>{{errors.seasonYear}}</small></label>
<label>Yards per Route Run<InputNumber v-model="form.yardsPerRouteRun" :minFractionDigits="2" :maxFractionDigits="3" /><small>{{errors.yardsPerRouteRun}}</small></label><label>Receiving Grade<InputNumber v-model="form.receivingGrade" :minFractionDigits="1" :maxFractionDigits="2" /><small>{{errors.receivingGrade}}</small></label>
<label>Contested-Catch Rate<InputNumber v-model="form.contestedCatchRate" :maxFractionDigits="2" /><small>{{errors.contestedCatchRate}}</small></label><label>Behind-LOS Target Rate<InputNumber v-model="form.behindLosTargetRate" :maxFractionDigits="2" /><small>{{errors.behindLosTargetRate}}</small></label>
<label>Catch Rate<InputNumber v-model="form.catchRate" :maxFractionDigits="2" /><small>{{errors.catchRate}}</small></label><label>Missed Tackles Forced / Reception<InputNumber v-model="form.missedTacklesForcedPerReception" :maxFractionDigits="3" /><small>{{errors.missedTacklesForcedPerReception}}</small></label>
<label>YAC After Contact / Reception<InputNumber v-model="form.yacAfterContactPerReception" :maxFractionDigits="3" /><small>{{errors.yacAfterContactPerReception}}</small></label><label>Source Name<InputText v-model="form.sourceName" /><small>{{errors.sourceName}}</small></label>
<label>Source Type<Dropdown v-model="form.sourceType" :options="['MANUAL','CSV_IMPORT','LICENSED_PROVIDER','DERIVED','DPA','B4ME']" /></label><label>Source Reference<InputText v-model="form.sourceReference" /></label><label class="wide">Notes<InputText v-model="form.notes" /></label><label class="check"><Checkbox v-model="form.verified" binary /> Verified (backend permission applies)</label></div>
<template #footer><Button label="Cancel" severity="secondary" @click="emit('update:modelValue',false)"/><Button label="Save" :loading="saving" @click="submit"/></template></Dialog></template>
<style scoped>.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.grid label{display:grid;gap:.35rem}.wide{grid-column:1/-1}.check{display:flex!important;align-items:center;gap:.5rem}small{color:var(--red-500)}@media(max-width:700px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}}</style>
